services:
  # Frontend (Next.js)
  betfront:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://213.199.59.34:5001
    container_name: nba-betfront
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nba_network

networks:
  nba_network:
    external: true
